//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EaterCake.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EaterCake.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 01:伐折羅
        ///02:漢尼拔侵蝕種
        ///03:鬼面巨尾
        ///04:接合體
        ///05:地繭女
        ///06:金剛
        ///07:葛波洛‧葛波洛
        ///08:蚩尤
        ///09:沙利葉
        ///0A:劍欄之矛
        ///0B:雙輪戰車
        ///0C:烏洛波羅斯
        ///0D:地母波里提毗
        ///0E:鬼面巨尾墮天
        ///0F:伐折羅巨尾(火)
        ///10:亞爾達諾瓦
        ///11:亞爾達諾瓦
        ///12:伐折羅巨尾(雷)
        ///13:地繭女墮天(火)
        ///14:地繭女墮天(冰)
        ///15:地繭女墮天(雷)
        ///16:接合體墮天(火)
        ///17:接合體墮天(冰)
        ///18:接合體墮天(雷)
        ///19:葛波洛‧葛波洛墮天(火)
        ///1A:葛波洛‧葛波洛墮天(冰)
        ///1B:金剛墮天
        ///1C:破顏金剛
        ///1D:蚩尤墮天
        ///1E:賽克邁特
        ///1F:天上君父
        ///20:劍欄之矛墮天(火)
        ///21:劍欄之矛墮天(雷)
        ///22:沙利葉墮天
        ///23:埃忒耳
        ///24:雙輪戰車墮天
        ///25:特斯卡特利波卡
        ///26:烏洛波羅斯墮天
        ///27:亞爾達諾瓦墮天
        ///28:亞爾達諾瓦墮天
        ///29:須佐之男
        ///2A:波塞頓
        ///2B:宙斯
        ///2C:希拉
        ///2D:葛波洛‧葛波洛黃金
        ///2E:天照
        ///2F:月讀
        ///30:漢尼拔
        ///31:維納斯
        ///3 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Monster_ID_Name_1_CN {
            get {
                return ResourceManager.GetString("Monster_ID_Name_1_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 01:伐折羅
        ///02:漢尼拔侵蝕種
        ///03:鬼面巨尾
        ///04:接合體
        ///05:地繭女
        ///06:金剛
        ///07:葛波洛‧葛波洛
        ///08:蚩尤
        ///09:沙利葉
        ///0A:劍欄之矛
        ///0B:雙輪戰車
        ///0C:烏洛波羅斯
        ///0D:地母波里提毗
        ///0E:鬼面巨尾墮天
        ///0F:伐折羅巨尾(火)
        ///10:亞爾達諾瓦
        ///11:亞爾達諾瓦
        ///12:伐折羅巨尾(雷)
        ///13:地繭女墮天(火)
        ///14:地繭女墮天(冰)
        ///15:地繭女墮天(雷)
        ///16:接合體墮天(火)
        ///17:接合體墮天(冰)
        ///18:接合體墮天(雷)
        ///19:葛波洛‧葛波洛墮天(火)
        ///1A:葛波洛‧葛波洛墮天(冰)
        ///1B:金剛墮天
        ///1C:破顏金剛
        ///1D:蚩尤墮天
        ///1E:賽克邁特
        ///1F:天父狄阿烏斯
        ///20:劍欄之矛墮天(火)
        ///21:劍欄之矛墮天(雷)
        ///22:沙利葉墮天
        ///23:埃忒耳
        ///24:雙輪戰車墮天
        ///25:特斯卡特利波卡
        ///26:烏洛波羅斯墮天
        ///27:亞爾達諾瓦墮天
        ///28:亞爾達諾瓦墮天
        ///29:須佐之男
        ///2A:波塞頓
        ///2B:宙斯
        ///2C:希拉
        ///2D:葛波洛‧葛波洛黃金
        ///2E:天照
        ///2F:月讀
        ///30:漢尼拔
        ///31:維納斯        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Monster_ID_Name_2_CN {
            get {
                return ResourceManager.GetString("Monster_ID_Name_2_CN", resourceCulture);
            }
        }
    }
}
